#pragma config(Sensor, dgtl3,  chooSwitch,     sensorDigitalIn)
#pragma config(Sensor, dgtl4,  wingusSwitch,   sensorDigitalIn)
#pragma config(Motor,  port1,           choo1,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           feedMe,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           right1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           left1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           left2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           choo2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           seymore,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           choo3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          right2,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

enum catapultState { REST, MOVING, STILL, MANUAL_OVERRIDE };
catapultState chooState = REST;

int chooSpeed;

void setFeedSpeed(int speed)
{
	motor[feedMe] = speed;
	motor[seymore] = speed;
}

void setChooSpeed(int speed)
{
	motor[choo1] = speed;
	motor[choo2] = speed;
	motor[choo3] = speed;
}

void cataChooChoo()
{
	if ((chooState == REST || chooState == MOVING) && vexRT[Btn5U] == 1)
	{
		chooState = MOVING;
		clearTimer(T2);
	}
	else if (chooState == MOVING && SensorValue[chooSwitch] == 0 && time1[T2] > 750)
	{
		chooState = STILL;
	}
	else if (chooState == MANUAL_OVERRIDE && vexRT[Btn5D] == 0)
	{
		chooState = STILL;
	}

	if (vexRT[Btn5D] == 1)
	{
		chooState = MANUAL_OVERRIDE;
	}

	switch (chooState)
	{
	case REST:
		chooSpeed = 0;
		break;
	case MOVING:
		chooSpeed = 127;
		break;
	case STILL:
		chooSpeed = 15;
		break;
	case MANUAL_OVERRIDE:
		chooSpeed = 127;
		break;
	default:
		chooSpeed = 0;
	}

	setChooSpeed(chooSpeed);
}

void fireFromBlocking()
{
	//bring ball to top of feed
	while (SensorValue[wingusSwitch] == 1)
	{
			setFeedSpeed(127);
	}
	setFeedSpeed(0);

	//cock catapult
	chooState = MOVING;
	clearTimer(T2);
	while (chooState != STILL)
	{
		cataChooChoo();
	}

	//load ball
	while (SensorValue[wingusSwitch] == 0)
	{
		setFeedSpeed(127);
	}

	//fire
	chooState = MOVING;
	while (chooState != STILL)
	{
		cataChooChoo();
	}
}

task main()
{
	//move catapult to blocking position
	chooState = MOVING;
	clearTimer(T2);
	while (chooState != STILL)
	{
		cataChooChoo();
	}

	for (int i = 0; i < 4; i++)
	{
		fireFromBlocking();
	}
}
