#pragma config(Sensor, dgtl1,  flywheelEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  feedSwitch,     sensorDigitalIn)
#pragma config(Motor,  port1,           ce,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rb,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           er,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           us,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rfdrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rbdrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lfdrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lbdrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           feedMe,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          seymore,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#define maxAcc 30 //the maximum amount a motor's power value can be safely changed in .1 seconds
#define fireErrorMargin .05 //percent error allowable in flywheel velocity for firing
#define sampleTime 50 //number of milliseconds between sampling the flywheel velocity and control adjustments in flywheel task
#define gearRatio 3 //gear ratio between flywheelEncoder and flywheel
//PID constants
#define kp 1 //TO TUNE
#define ki 1 //TO TUNE
#define kd 1 //TO TUNE
#define firingErrorMargin .05 //TO TUNE
#define bangBangErrorMargin .1 //TO TUNE
#define integralMargin .075 //TO TUNE

#define fireBtn Btn5U
#define continuousFireBtn Btn5D
#define stopFireBtn Btn5U
#define punchBtn Btn5U
#define feedInBtn Btn6U
#define feedOutBtn Btn6D
#define switchLauncherModesBtn Btn8L
#define emergencyStopBtn Btn8R

bool flywheelRunning = false;
bool velocityUpdated = false;
bool continuousFire = false;
float flywheelVelocity = 0;
float targetVelocity = 0;
int flywheelPower = 0;
int targetPower = 0;
int defaultPower = 0;

//begin helper functions region
int limit(int input, int max, int min) {
	if (abs(input) <= max && abs(input) >= min) {
		return input;
	}	else {
		return ((abs(input) > max) ? (max * sgn(input)) : (min * sgn(input)));
	}
}

bool shouldFire() {
	if (continuousFire)	{
		if (vexRT[stopFireBtn] == 0) {
			return true;
		} else {
			continuousFire = false;
			return false;
		}
	}	else if (vexRT[fireBtn] == 1)	{
		return true;
	}	else {
		return false;
	}
}

task calcVelocity() {
	while (true) {
		SensorValue[flywheelEncoder] = 0;
		wait1Msec(sampleTime);
		flywheelVelocity = SensorValue[flywheelEncoder] * gearRatio / sampleTime;
		velocityUpdated = true;
	}
}

float getFlywheelVelocity() {
	velocityUpdated = false;
	return flywheelVelocity;
}
//end helper functions region

//set functions region
void setFeedPower(int bottom, int top) {
	motor[feedMe] = top;
	motor[seymore] = bottom;
}

void setDrivePower(int right, int left) {
	motor[rfdrive] = right;
	motor[rbdrive] = right;
	motor[lfdrive] = left;
	motor[lbdrive] = left;
}

void setLauncherPower(int power) {
	int adjustedPower = limit(power, 0, 127) * (flywheelRunning ? 1 : -1);
	motor[ce] = adjustedPower;
	motor[rb] = adjustedPower;
	motor[er] = adjustedPower;
	motor[us] = adjustedPower;
	flywheelPower = adjustedPower;
}

task spinUpControl() {
	while (targetPower == flywheelPower) { EndTimeSlice(); }
	while (targetPower - flywheelPower > maxAcc)
	{
		setLauncherPower(flywheelPower + maxAcc);
		wait1Msec(100);
	}
}
//end set functions region

//begin user input region
task feedControl() {
	while (vexRT[feedInBtn] == 0 && vexRT[feedOutBtn] == 0) { EndTimeSlice(); }
	if (vexRT[feedInBtn] == 1) {
		setFeedPower(127, (SensorValue[feedSwitch] == 1 ? 127 : 0));
		while (vexRT[feedInBtn] == 1) { EndTimeSlice(); }
	} else {
		setFeedPower(-127, -127);
		while (vexRT[feedOutBtn] == 1) { EndTimeSlice(); }
	}
	setFeedPower(0, 0);
}

task puncher() {
	while (true)
	{
		while (vexRT[punchBtn] == 0) { EndTimeSlice(); }
		setLauncherPower(127);
		while (vexRT[punchBtn] == 1) { EndTimeSlice(); }
		setLauncherPower(0);
	}
}

task flywheel() {
	TVexJoysticks buttons[4] = {Btn7D, Btn7L, Btn7R, Btn7U}; //creating a pseudo-hash associating buttons with velocities and default motor powers
	float velocities[4] = {0, 0, 0, 0};
	int defaultPowers[4] = {0, 0, 0, 0};

	while (true)
	{
		for (int i = 0; i < 4; i++)
		{
			if (vexRT[buttons[i]] == 1)
			{
				targetVelocity = velocities[i];
				defaultPower = defaultPowers[i];
			}
			EndTimeSlice();
		}
	}
}

task flywheelStabilization() { //modulates motor powers to maintain constant flywheel velocity
	float prevError;
	float error;
	float integral;

	while (true)
	{
		prevError = targetVelocity - getFlywheelVelocity();
		integral = 0;

		while (abs(flywheelVelocity - getFlywheelVelocity()) * gearRatio < bangBangErrorMargin * flywheelVelocity) //PID control
		{
			wait1Msec(sampleTime);
			while (!velocityUpdated) { EndTimeSlice(); }
			error = (flywheelVelocity - getFlywheelVelocity()) * gearRatio;

			if (abs(error) < integralMargin * flywheelVelocity)
			{
				integral += error;
			}

			targetPower = defaultPower + kp * error + ki * integral + kd * (error - prevError) / sampleTime;
			prevError = error;
		}

		//bang bang control
		setLauncherPower((flywheelVelocity < flywheelVelocity) ? (127) : (0));

		while (abs(flywheelVelocity - flywheelVelocity * gearRatio) > bangBangErrorMargin * flywheelVelocity) { EndTimeSlice(); }

		setLauncherPower(defaultPower);
	}
}
//end user input region

//begin autobehaviors region
task feedToTop() { //loads a ball
	stopTask(feedControl);
	setFeedPower(0, 0);
	while (true) {
		while (SensorValue[feedSwitch] == 0) { EndTimeSlice(); }
		setFeedPower(127, 127);
		while (SensorValue[feedSwitch] == 1) { EndTimeSlice(); }
		setFeedPower(0, 0);
	}
}

task fireControl() { //waits for ideal launch conditions and then fires
	while (true) {
		while (vexRT[continuousFireBtn] == 0 && vexRT[fireBtn] == 0) { EndTimeSlice(); }
		continuousFire = vexRT[continuousFireBtn] == 1;
		do {
			startTask(feedToTop);
			while (SensorValue[feedSwitch] == 1 && abs(targetVelocity - flywheelVelocity) < targetVelocity * fireErrorMargin && shouldFire()) { EndTimeSlice(); }
			if (shouldFire()) {
				stopTask(feedToTop);
				setFeedPower(0, 127);
				while (SensorValue[feedSwitch] == 0 && shouldFire()) { EndTimeSlice(); } //eventually transition to motor velocity detection
				setFeedPower(0, 0);
			}
		} while(shouldFire() && continuousFire);
		stopTask(feedToTop);
	}
}
//end autobehaviors region

//begin task control region
task launcherMode() {
	while (vexRT[switchLauncherModesBtn] == 0) { EndTimeSlice(); }
	flywheelRunning = !flywheelRunning;
	if (flywheelRunning) {
		stopTask(puncher);
		startTask(flywheel);
		startTask(flywheelStabilization);
		startTask(spinUpControl);
		startTask(fireControl);
		startTask(calcVelocity);
	}	else {
		stopTask(flywheel);
		stopTask(flywheelStabilization);
		stopTask(spinUpControl);
		stopTask(fireControl);
		stopTask(calcVelocity);
		startTask(puncher);
	}
}

void initializeTasks() {
	if (flywheelRunning) {
		startTask(flywheel);
		startTask(flywheelStabilization);
		startTask(spinUpControl);
		startTask(fireControl);
		startTask(calcVelocity);
	}	else {
		startTask(puncher);
	}
	startTask(launcherMode);
	startTask(feedControl);
}

void emergencyStop() {
	stopTask(flywheel);
	stopTask(flywheelStabilization);
	stopTask(puncher);
	stopTask(feedControl);
	stopTask(spinUpControl);
	stopTask(fireControl);
	stopTask(calcVelocity);
	stopTask(launcherMode);
	stopTask(feedToTop);

	initializeTasks();
}
//end task control region

void pre_auton() { bStopTasksBetweenModes = true; }

task autonomous() {
	AutonomousCodePlaceholderForTesting();
}

task usercontrol() {
	initializeTasks();

	while (true)
	{
		while (vexRT[emergencyStopBtn] == 0)
		{
			setDrivePower(vexRT[Ch2], vexRT[Ch3]);
			EndTimeSlice();
		}

		emergencyStop();
	}
}
