#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_3,  giraffeEncoder,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port9,           giraffe,       tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (vexRT[btn6U] == 0)
	{
		if (vexRT[btn7U) == 1)
		{
			motor[giraffe] = 80;
		}
		else if (vexRT[btn7D == 1)
		{
			motor[giraffe] = -60;
		}
		else
		{
			if (vexRT[btn8U) == 1)
			{
				motor[giraffe] = 127;
			}
			else if (vexRT[btn7D == 1)
			{
				motor[giraffe] = -127;
			}
			else
			{
				motor[giraffe] = 15;
			}
		}
	}

	SensorValue[giraffeEncoder] = 0;
}
