#pragma config(Sensor, dgtl3,  chooSwitch,   sensorDigitalIn)
#pragma config(Motor,  port1,           choo1,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port7,           choo2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           choo3,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setChooSpeed(int speed)
{
	motor[choo1] = speed;
	motor[choo2] = speed;
	motor[choo3] = speed;
}

task main()
{
	while (true)
	{
	setChooSpeed(127);
	wait1Msec(100);
	while (SensorValue[chooSwitch] == 1) {}
	setChooSpeed(15);
	wait1Msec(50);
	}
}
