#pragma config(Sensor, in1,    Yaw,            sensorGyro)
#pragma config(Sensor, in2,    BallFeed,       sensorLineFollower)
#pragma config(Sensor, in3,    BallLaunch,     sensorLineFollower)
#pragma config(Sensor, in4,    modePot,        sensorPotentiometer)
#pragma config(Sensor, in5,    sidePot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  flywheelEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftE,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightE,         sensorQuadEncoder)
#pragma config(Motor,  port1,           Seymore,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lfd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lbd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ce,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rb,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           er,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           us,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rbd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          FeedMe,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define feedInBtn Btn6U
#define feedOutBtn Btn6D
#define upTwentyBtn Btn5U
#define downTwentyBtn Btn5D
#define upTenBtn Btn5U
#define downTenBtn Btn5D
#define upFiveBtn Btn7U
#define downFiveBtn Btn7D
#define upOneBtn Btn8U
#define downOneBtn Btn8D

#define sampleTime 60 //50

float velocity = 0.0;
float velocities[5] = {0, 0, 0, 0, 0};
int flywheelPower;
float battBatt;
float avgBatt;
int limit(int input, int min, int max)
{
	if (abs(input) <= max && abs(input) >= min)
	{
		return input;
	}
	else
	{
		return ((abs(input) > max) ? (max * sgn(input)) : (min * sgn(input)));
	}
}

void setFeedPower(int power)
{
	motor[feedMe] = power;
	motor[seymore] = power;
}

void setLauncherPower(int power) {
	flywheelPower = limit(power, 0, 127);
	motor[ce] = flywheelPower;
	motor[rb] = flywheelPower;
	motor[er] = flywheelPower;
	motor[us] = flywheelPower;
}

void setDrivePower(int right, int left) {
	motor[rfd] = right;
	motor[rbd] = right;
	motor[lfd] = left;
	motor[lbd] = left;
}

void spinUp()
{
	for (int power = 30; power <= 90; power += 30)
	{
		setLauncherPower(power);
		wait1Msec(3000);
	}
}

void rampDrive(int targetPower, int rampTime) {
	for (int power = (int)(targetPower * 100/ rampTime); power < targetPower; power += (int)(targetPower * 100/ rampTime)) {
		setDrivePower(power, power);
		wait1Msec(100);
	}

	setDrivePower(targetPower, targetPower);
}

task feedControl()
{
	while (true)
	{
		while (vexRT[feedInBtn] == 0 && vexRT[feedOutBtn] == 0) { EndTimeSlice(); }
		if (vexRT[feedInBtn] == 1)
		{
			setFeedPower(127);
			while (vexRT[feedInBtn] == 1) { EndTimeSlice(); }
		}
		else
		{
			setFeedPower(-127);
			while (vexRT[feedOutBtn] == 1) { EndTimeSlice(); }
		}
		setFeedPower(0);
	}
}

task calcVelocity()
{
	while (true)
	{
		for (int i = 0; i < 5; i++)
		{
			SensorValue[flywheelEncoder] = 0;
			wait1Msec(sampleTime);
			velocities[i] = (float)(SensorValue[flywheelEncoder]) /*/ (float)(sampleTime)*/;
			velocity = (velocities[0] + velocities[1] + velocities[2] + velocities[3] + velocities[4]) / 5;
		}
	}
}

task main()
{
	/*rampDrive(127, 1500);
	wait1Msec(2000);
	setDrivePower(0, 0);*/

	int power = 90;
	//spinUp();
	startTask(feedControl);
	startTask(calcVelocity);
	while (true)
	{
		if (vexRT[upTwentyBtn])
		{
			power += 20;
			while (vexRT[upTwentyBtn] == 1) { EndTimeSlice(); }
		}
		else if (vexRT[upTenBtn])
		{
			power += 10;
			while (vexRT[upTenBtn] == 1) { EndTimeSlice(); }
		}
		else if (vexRT[upFiveBtn])
		{
			power += 5;
			while (vexRT[upFiveBtn] == 1) { EndTimeSlice(); }
		}
		else if (vexRT[upOneBtn])
		{
			power += 1;
			while (vexRT[upOneBtn] == 1) { EndTimeSlice(); }
		}
		else if (vexRT[downTwentyBtn])
		{
			power -= 20;
			while (vexRT[downTwentyBtn] == 1) { EndTimeSlice(); }
		}
		else if (vexRT[downTenBtn])
		{
			power -= 10;
			while (vexRT[downTenBtn] == 1) { EndTimeSlice(); }
		}
		else if (vexRT[downFiveBtn])
		{
			power -= 5;
			while (vexRT[downFiveBtn] == 1) { EndTimeSlice(); }
		}
		else if (vexRT[downOneBtn])
		{
			power -= 1;
			while (vexRT[downOneBtn] == 1) { EndTimeSlice(); }
		}

		battBatt = nImmediateBatteryLevel;
		avgBatt = nAvgBatteryLevel;
		setLauncherPower(power);
		setDrivePower(vexRT[Ch2], vexRT[Ch3]);
		EndTimeSlice();
	}
}
