#pragma config(Motor,  port1,           launcher1,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           launcher2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           launcher3,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           launcher4,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lfd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lbd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rbd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           feed1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          feed2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void setLauncherPower(int power) {
	motor[launcher1] = power;
	motor[launcher2] = power;
	motor[launcher3] = power;
	motor[launcher4] = power;
}

void pre_auton() { bStopTasksBetweenModes = true; }

task autonomous() {
	setLauncherPower(127);
	wait1Msec(1750);
	setLauncherPower(0);
}

task usercontrol() {
	while (true) {
	  motor[lfd]  = vexRT[Ch2];  // (y + x)/2
    motor[lbd] = vexRT[Ch2];  // (y - x)/2
    motor[rfd]  = vexRT[Ch3];  // (y + x)/2
    motor[rbd] = vexRT[Ch3];  // (y - x)/2
		//launch control
		if(vexRT[Btn7U] == 1)
		{
			setLauncherPower(-30);
		}
	 if(vexRT[Btn7R] == 1)
		{
			setLauncherPower(-60);
		}
		if(vexRT[Btn7D] == 1)
		{
			setLauncherPower(-90);
		}
		if(vexRT[Btn7L] == 1)
		{
			setLauncherPower(-120);
		}
		if(vexRT[Btn8U] == 1)
		{
			setLauncherPower(120);
		}
		if(vexRT[Btn8D] == 1)
		{
			setLauncherPower(0);
		}
		// rear feed control
		if(vexRT[Btn5U] == 1)
		{
			motor[feed2] = 127;

		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[feed2] = -127;
		}
		else
		{
			motor[feed2] = 0;
		}
		// front feed control
		if(vexRT[Btn6U] == 1)
		{
			motor[feed1] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[feed1] = -127;
		}
		else
		{
			motor[feed1] = 0;
		}
	}
}
