#pragma config(Motor,  port1,           choo,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		if (vexRT[Btn5U])
		{
			motor[choo] = 127;
		}
		else if (vexRT[Btn5D])
		{
			motor[choo] = -127;
		}
		else
		{
			motor[choo1] = 0;
		}
	}
}
