#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    chooResistor,   sensorReflection)
#pragma config(Sensor, in2,    cataResistor,   sensorReflection)
#pragma config(Sensor, dgtl1,  chooSwitch,     sensorDigitalIn)
#pragma config(Sensor, dgtl2,  feedSwitch,     sensorDigitalIn)
#pragma config(Sensor, I2C_1,  giraffeEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  rightEncoder,   sensorNone)
#pragma config(Motor,  port1,           feedMe,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           seymore,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           left1,         tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           left2,         tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           choo1,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           cata,          tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           right1,        tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port8,           right2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           giraffe,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          choo2,         tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int stillSpeed = 15;
const int feedBackwardTime = 250;
const int resistorCutoff = 700;

bool cockCatapultRunning = false;
bool feedToTopRunning = false;
bool loadRunning = false;

void setFeedPower(int power)
{
	motor[feedMe] = power;
	motor[seymore] = power;
}

void setChooPower(int power)
{
	motor[choo1] = power;
	motor[choo2] = power;
}

task cockCatapult()
{
	setChooPower((SensorValue[chooSwitch] == 1) ? (127) : (0));
	cockCatapultRunning = true;
	while (SensorValue[chooSwitch] == 1) { EndTimeSlice(); }
	setChooPower(stillSpeed);
	cockCatapultRunning = false;
}

task feedToTop()
{
	setFeedPower((SensorValue[feedSwitch] == 1) ? (127) : (0));
	feedToTopRunning = true;
	while (SensorValue[feedSwitch] == 1) { EndTimeSlice() ;}
	setFeedPower(0);
	feedToTopRunning = false;
}

task main()
{
	while (true)
	{
		while (vexRT[Btn8L] == 0) {}
		loadRunning = true;

		startTask(cockCatapult);
		startTask(feedToTop);
		while (cockCatapultRunning || feedToTopRunning) { EndTimeSlice(); }

		setFeedPower(127);

		while (SensorValue[chooResistor] < resistorCutoff) { EndTimeSlice(); }

		if (SensorValue[feedSwitch] == 0)
		{
			setFeedPower(-127);
			wait1Msec(feedBackwardTime);
		}
		setFeedPower(0);

		loadRunning = false;
	}
}
