#pragma config(Sensor, dgtl1,  giraffeEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  chooSwitch,     sensorDigitalIn)
#pragma config(Sensor, dgtl4,  feedSwitch,     sensorDigitalIn)
#pragma config(Motor,  port1,           choo1,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           feedMe,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           seymore,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           right1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           left1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           left2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           choo2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           choo3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           giraffe,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right2,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

enum catapultState { BLOCKING, STILL, MANUAL_OVERRIDE };
catapultState chooState = BLOCKING;

int giraffeTarget;

const TButtonMasks progressCataChooChooBtn = Btn5U;
const TButtonMasks manualOverrideBtn = Btn5D;
const TButtonMasks feedUpBtn = Btn6U;
const TButtonMasks feedDownBtn = Btn6D;
const TButtonMasks fireBtn = Btn8D;
const TButtonMasks feedToTopBtn = Btn8U;
const TButtonMasks continuousFeedBtn = Btn8L;
const TButtonMasks continuousCatapultBtn = Btn8R;
const TButtonMasks emergencyStopBtnOne = Btn7L;
const TButtonMasks emergencyStopBtnTwo = Btn7U;
const TButtonMasks reverseManualOverrideBtn = Btn7D;
const TButtonMasks giraffeUpBtn = Btn7U;
const TButtonMasks giraffeDownBtn = Btn7D;
const TButtonMasks fullCourtBtn = Btn7L;
const TButtonMasks netBtn = Btn7R;

const int fireDuration = 750; //amount of time motors run during firing
const int stillSpeed = 15; //rename chooStillSpeed
const int giraffeStillSpeed = 15; //maybe change value depending on position of motor
const int buttonDelay = 750;
const int giraffeUpwardSpeed = 100;
const int giraffeDownwardSpeed = -80;
const int startingSquare = 70;
const int fullCourt = 80;
const int net = 40;

//set functions region
void setFeedSpeed(int speed)
{
	motor[feedMe] = speed;
	motor[seymore] = speed;
}

void setChooSpeed(int speed)
{
	motor[choo1] = speed;
	motor[choo2] = speed;
	motor[choo3] = speed;
}

void setDriveSpeed(int right, int left)
{
	motor[right1] = right;
	motor[right2] = right;
	motor[left1] = left;
	motor[left2] = left;
}
//end set functions region

//autoBehaviors region
task cockCatapult()
{
	setChooSpeed((SensorValue[chooSwitch] == 1) ? (127) : (stillSpeed));
	while (SensorValue[chooSwitch] == 1) { EndTimeSlice(); }
	setChooSpeed(stillSpeed);
}

task feedToTop()
{
	setFeedSpeed((SensorValue[feedSwitch] == 1) ? (127) : (0));
	while (SensorValue[feedSwitch] == 1) { EndTimeSlice(); }
	setFeedSpeed(0);
}
//end autoBehaviors region

task main()
{
	while (true)
	{
		/* fire
		while (vexBtn[fireBtn] == 0) { EndTimeSlice(); }

		startTask(cockCatapult);
		startTask(feedToTop);
		while (SensorValue[chooSwitch] == 1 || SensorValue[feedSwitch] == 1) { EndTimeSlice(); }

		setFeedSpeed(127);
		while (SensorValue[feedSwitch] == 0 || vexRT[fireBtn] == 1) { EndTimeSlice(); }
		wait1Msec(750);
		setFeedSpeed(-127);
		wait1Msec(250);
		setFeedSpeed(0);
		setChooSpeed(127);
		wait1Msec(fireDuration);
		setChooSpeed(0);
		*/

		/* feedToTop
		while (vexBtn[feedToTopBtn] == 0) { EndTimeSlice(); }

		setFeedSpeed((SensorValue[feedSwitch] == 1) ? (127) : (0));
		while (SensorValue[feedSwitch] == 1) { EndTimeSlice(); }
		setFeedSpeed(0);
		*/

		/* continuous feed
		while (vexBtn[continuousFeedBtn] == 0) { EndTimeSlice(); }

		setFeedSpeed(127);
		while(vexRT[continuousFeedBtn] == 1) { EndTimeSlice(); } //waits for button to be released
		while(vexRT[continuousFeedBtn] == 0) { EndTimeSlice(); }
		setChooSpeed(0);
		*/

		/* continuous catapult
		while (vexBtn[continuousCatapultpBtn] == 0) { EndTimeSlice(); }

		stopTask(cataChooChoo);
		setChooSpeed(127);
		while(vexRT[continuousCatapultBtn] == 1) { EndTimeSlice(); } //waits for button to be released; can be replaced by wait1Msec(buttonDelay);
		while(vexRT[continuousCatapultBtn] == 0) { EndTimeSlice(); }
		setChooSpeed(0);
		*/

		/* cock catapult
		while (vexBtn[progressCataChooChooBtn] == 0) { EndTimeSlice(); }

		setChooSpeed((SensorValue[chooSwitch] == 1) ? (127) : (stillSpeed));
		while (SensorValue[chooSwitch] == 1) { EndTimeSlice(); }
		setChooSpeed(stillSpeed);
		*/
	}
}
