#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_3,  giraffeEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port3,           left1,         tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port4,           left2,         tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           choo1,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           right1,        tmotorVex393_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port8,           right2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           giraffe,       tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port10,          choo2,         tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int giraffeUpwardPower = 127;
const int giraffeDownwardPower = -80;

void setChooPower(int power)
{
	motor[choo1] = power;
	motor[choo2] = power;
}

void setDrivePower(int right, int left)
{
	motor[right1] = right;
	motor[right2] = right;
	motor[left1] = left;
	motor[left2] = left;
}

task main()
{
	int giraffePosition = SensorValue[giraffeEncoder];

	while (true)
	{
		setDrivePower(vexRT[Ch2], vexRT[Ch3]);

		if (vexRT[Btn5U] == 1)
		{
			motor[giraffe] = giraffeUpwardPower;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[giraffe] = giraffeDownwardPower;
		}
		else
		{
			motor[giraffe] = 15;
		}

		if (vexRT[Btn6U] == 1)
		{
				setChooPower(127);
		}
		else
		{
			setChooPower(15);
		}

		giraffePosition = SensorValue[giraffeEncoder];
	}
}
