#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_3,    giraffeEncoder,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port5,           choo1,         tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port10,          choo2,         tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port9,           giraffe,       tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setChooPower(int power)
{
	motor[choo1] = power;
	motor[choo2] = power;
}

task main()
{
	int giraffePosition = SensorValue[giraffeEncoder];

	while (true)
	{
		setDrivePower(vexRT[Ch2], vexRT[Ch3]);

		if (vexRT[Btn5U] == 1)
		{
			motor[giraffe] = giraffeUpwardPower;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[giraffe] = giraffeDownwardPower;
		}
		else
		{
			motor[giraffe] = 0;
		}

		if (vexRT[Btn6U] == 1)
		{
				setChooPower(127);
		}
		else
		{
			setChooPower(0);
		}

		giraffePosition = SensorValue[giraffeEncoder];
	}
}
