#pragma config(Sensor, dgtl1,  flyEncoder,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  wheelEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           fly,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           wheel,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
const float pcoeff = .5;
const float icoeff = .5;
const float dcoeff = .5;

float targetSpeed = 2.0;
long accumulation = 0;

typedef struct
{
	int power;
	float speed;
	tSensors encoder;
	TTimers timer;
	tMotor motor;
} flywheel;

void setLauncherSpeed (int flySpeed, int wheelSpeed)
{
	motor[fly] = flySpeed;
	motor[wheel] = wheelSpeed;
}

float getWheelSpeed(tSensors wheelEncoder, TTimers timer)
{
	speed = SensorValue[wheelEncoder] / time1(timer);
	SensorValue[wheelEncoder] = 0;
	clearTimer(timer);
	return speed;
}

task main()
{
	flywheel fly;
	fly.power = 0;
	fly.speed = 0.0;
	fly.encoder = flyEncoder;
	fly.timer = T1;
}
