#pragma config(Sensor, dgtl1,  chooEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           choo1,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port7,           choo2,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int encoderValue = 0;

task main()
{
	SensorValue[chooEncoder] = 0;
	while (true) {
		encoderValue = SensorValue[chooEncoder];
		if (vexRT[Btn5U]==1)
		{
			motor[choo1] = 127;
			motor[choo2] = 127;
		}
		else if (vexRT[Btn5D]==1)
		{
			motor[choo1] = 75;
			motor[choo2] = 75;
		}
		else
		{
			motor[choo1] = 0;
			motor[choo2] = 0;
		}
	}
}
